### PR TITLE
KS-107: payment types support; tests

### PR DESCRIPTION
**Pull request by boyankukushev**
Only the `Mercado Pago` payment type still missing.

### CODE REVIEW

**Review by leykov — APPROVED** [review]
All looks good.

**Review by preslav-anev — APPROVED** [review]
I approve this pull-request.

**Comment by gallilama** [comment]
Regarding Mercado Pago, the PTYP value should be MERCADE_PAGO.  The API docs are accurate.

**Review by gallilama — APPROVED** [review]
See my prev comment re: Mercado Pago

**Pull request merged**
